// Data Engineering Learning Path - Module Definitions
// Each module has: id, title, description, icon, level (row in DAG), column position,
// dependencies (edges), type (sql/python/quiz), and color

const modules = [
  // ===== Level 0: Foundations =====
  {
    id: "sql-fundamentals",
    title: "SQL Fundamentals",
    shortTitle: "SQL Basics",
    description: "Master SELECT, WHERE, ORDER BY, GROUP BY, JOINs, and aggregation functions.",
    icon: "db",
    level: 0,
    col: 0,
    deps: [],
    type: "sql",
    questionFilter: { ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    color: "#3b82f6",
  },
  {
    id: "python-basics",
    title: "Python Fundamentals",
    shortTitle: "Python Basics",
    description: "Learn core Python: data types, loops, functions, string manipulation, and collections.",
    icon: "py",
    level: 0,
    col: 1,
    deps: [],
    type: "python",
    questionFilter: { ids: [1, 2, 3, 4, 5, 6, 7] },
    color: "#eab308",
  },
  {
    id: "linux-shell",
    title: "Linux & Shell Scripting",
    shortTitle: "Linux / Shell",
    description: "Navigate the command line, write shell scripts, and manage files & processes.",
    icon: "terminal",
    level: 0,
    col: 2,
    deps: [],
    type: "quiz",
    color: "#22c55e",
  },

  // ===== Level 1: Intermediate =====
  {
    id: "advanced-sql",
    title: "Advanced SQL",
    shortTitle: "Advanced SQL",
    description: "Window functions, CTEs, recursive queries, RANK, LAG/LEAD, and analytical patterns.",
    icon: "db",
    level: 1,
    col: 0,
    deps: ["sql-fundamentals"],
    type: "sql",
    questionFilter: { ids: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30] },
    color: "#6366f1",
  },
  {
    id: "python-de",
    title: "Python for Data Engineering",
    shortTitle: "Python for DE",
    description: "Advanced Python: data structures, algorithms, file I/O patterns for data pipelines.",
    icon: "py",
    level: 1,
    col: 1,
    deps: ["python-basics"],
    type: "python",
    questionFilter: { ids: [8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 20, 21, 22, 23, 24, 25, 29, 30, 31, 32, 33, 40, 41, 42, 45, 46, 47, 48, 49, 51, 52, 53, 55, 56, 57, 59, 60, 62, 63, 64, 65] },
    color: "#f59e0b",
  },
  {
    id: "git",
    title: "Git & Version Control",
    shortTitle: "Git / VCS",
    description: "Branching, merging, rebasing, pull requests, and collaborative workflows.",
    icon: "git",
    level: 1,
    col: 2,
    deps: ["linux-shell"],
    type: "quiz",
    color: "#ef4444",
  },

  {
    id: "sql-de",
    title: "SQL for Data Engineering",
    shortTitle: "SQL for DE",
    description: "DE-focused SQL: deduplication, SCD types, CDC, data lineage, pipeline monitoring, star schemas, and skew detection.",
    icon: "db",
    level: 1,
    col: 3,
    deps: ["sql-fundamentals"],
    type: "sql",
    questionFilter: { ids: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55] },
    color: "#0891b2",
  },
  {
    id: "python-dsa-hard",
    title: "Python DSA - Hard Problems",
    shortTitle: "DSA Hard",
    description: "Hard DE DSA: 3Sum, sliding window max, meeting rooms, merge K lists, median of arrays, LRU cache, and more.",
    icon: "py",
    level: 1,
    col: 4,
    deps: ["python-basics"],
    type: "python",
    questionFilter: { ids: [17, 19, 27, 28, 34, 35, 38, 39, 43, 44, 50, 54, 58, 61] },
    color: "#dc2626",
  },

  // ===== Level 2: Core Data Engineering =====
  {
    id: "data-modeling",
    title: "Data Modeling",
    shortTitle: "Data Modeling",
    description: "Normalization, dimensional modeling, star & snowflake schemas, SCD types.",
    icon: "schema",
    level: 2,
    col: 0,
    deps: ["advanced-sql"],
    type: "quiz",
    color: "#8b5cf6",
  },
  {
    id: "etl",
    title: "ETL / ELT Fundamentals",
    shortTitle: "ETL / ELT",
    description: "Extract-Transform-Load patterns, data pipelines, batch vs streaming, idempotency.",
    icon: "pipeline",
    level: 2,
    col: 1,
    deps: ["advanced-sql", "python-de"],
    type: "quiz",
    color: "#14b8a6",
  },
  {
    id: "docker",
    title: "Docker & Containers",
    shortTitle: "Docker",
    description: "Containerization, Dockerfiles, docker-compose, images, volumes, and networking.",
    icon: "docker",
    level: 2,
    col: 2,
    deps: ["git", "linux-shell"],
    type: "quiz",
    color: "#0ea5e9",
  },

  // ===== Level 3: Ecosystem =====
  {
    id: "data-warehousing",
    title: "Data Warehousing",
    shortTitle: "Warehousing",
    description: "Warehouse architecture, columnar storage, partitioning, BigQuery / Redshift / Snowflake.",
    icon: "warehouse",
    level: 3,
    col: 0,
    deps: ["data-modeling"],
    type: "quiz",
    color: "#a855f7",
  },
  {
    id: "spark",
    title: "Apache Spark",
    shortTitle: "Spark",
    description: "Distributed computing, RDDs, DataFrames, transformations, actions, and Spark SQL.",
    icon: "spark",
    level: 3,
    col: 1,
    deps: ["python-de", "etl"],
    type: "quiz",
    color: "#f97316",
  },
  {
    id: "airflow",
    title: "Airflow & Orchestration",
    shortTitle: "Airflow",
    description: "DAG authoring, operators, sensors, scheduling, XComs, and pipeline orchestration.",
    icon: "airflow",
    level: 3,
    col: 2,
    deps: ["etl", "docker"],
    type: "quiz",
    color: "#06b6d4",
  },

  // ===== Level 4: Advanced =====
  {
    id: "cloud",
    title: "Cloud Platforms (AWS/GCP/Azure)",
    shortTitle: "Cloud / AWS / GCP",
    description: "S3, GCS, IAM, Lambda/Cloud Functions, managed services for data engineering.",
    icon: "cloud",
    level: 4,
    col: 0,
    deps: ["data-warehousing", "spark"],
    type: "quiz",
    color: "#ec4899",
  },
  {
    id: "kafka",
    title: "Streaming & Kafka",
    shortTitle: "Kafka / Streaming",
    description: "Event streaming, topics, producers, consumers, partitions, and real-time pipelines.",
    icon: "stream",
    level: 4,
    col: 1,
    deps: ["spark"],
    type: "quiz",
    color: "#10b981",
  },
  {
    id: "data-quality",
    title: "Data Quality & Testing",
    shortTitle: "Data Quality",
    description: "Data validation, Great Expectations, dbt tests, schema checks, and observability.",
    icon: "check",
    level: 4,
    col: 2,
    deps: ["etl", "airflow"],
    type: "quiz",
    color: "#84cc16",
  },

  // ===== Level 5: DevOps & Capstone =====
  {
    id: "cicd",
    title: "CI/CD for Data Pipelines",
    shortTitle: "CI/CD",
    description: "Automated testing, deployment pipelines, infrastructure-as-code, and monitoring.",
    icon: "rocket",
    level: 5,
    col: 1,
    deps: ["cloud", "airflow", "data-quality", "docker"],
    type: "quiz",
    color: "#f43f5e",
  },
];

module.exports = modules;
