// AI Engineer Roadmap - Module Definitions
// Progression: Foundations -> Prompting & LLMs -> Platforms & Models ->
//              Embeddings -> Retrieval & RAG -> Agents & Protocols -> Safety, Multimodal & Tools

const aimlModules = [
  // ===== Level 0: Foundations =====
  {
    id: "intro-ai-engineering",
    title: "Introduction to AI Engineering",
    shortTitle: "Intro to AI Eng",
    description: "What is an AI Engineer? Roles & responsibilities, impact on product development, and AI Engineer vs ML Engineer — differences, overlap, and collaboration.",
    icon: "brain",
    level: 0,
    col: 0,
    deps: [],
    type: "quiz",
    color: "#8b5cf6",
  },
  {
    id: "common-terminology",
    title: "Common Terminology",
    shortTitle: "Terminology",
    description: "The vocabulary of AI engineering: LLMs, embeddings, inference, tokens, vector databases, AI agents, RAG, fine-tuning, prompt engineering, and context engineering.",
    icon: "term",
    level: 0,
    col: 1,
    deps: ["intro-ai-engineering"],
    type: "quiz",
    color: "#a855f7",
  },
  {
    id: "core-llm-elements",
    title: "Core LLM Elements",
    shortTitle: "Core LLM",
    description: "How LLMs actually work: tokens, context windows, sampling parameters, temperature, top-K, top-P, and repetition penalties.",
    icon: "llm",
    level: 0,
    col: 2,
    deps: ["intro-ai-engineering"],
    type: "quiz",
    color: "#7c3aed",
  },

  // ===== Level 1: Prompting & LLMs =====
  {
    id: "prompt-engineering",
    title: "Prompt Engineering",
    shortTitle: "Prompt Eng",
    description: "Zero-shot, few-shot, chain-of-thought, ReAct, self-consistency, input/output formatting, function calling, prompt chaining, templates, guardrails, structured outputs, system prompts, data/context injection, and prompt evaluation.",
    icon: "prompt",
    level: 1,
    col: 0,
    deps: ["core-llm-elements"],
    type: "quiz",
    color: "#6366f1",
  },
  {
    id: "working-with-llms",
    title: "Working with LLMs",
    shortTitle: "Working w/ LLMs",
    description: "Fine-tuning, context engineering, and parameter tuning — the non-RAG techniques for getting higher-quality, more reliable results out of an LLM.",
    icon: "brain",
    level: 1,
    col: 1,
    deps: ["core-llm-elements"],
    type: "quiz",
    color: "#4f46e5",
  },

  // ===== Level 2: Platforms & Models =====
  {
    id: "platforms-ecosystem",
    title: "Platforms & Ecosystem",
    shortTitle: "Platforms",
    description: "Hugging Face (Tasks, Hub, Transformers), Ollama, LM Studio, OpenRouter, APIs & SDKs, OpenAI-compatible APIs, Anthropic/OpenAI/Google/open-source model APIs, and the Hugging Face Inference API.",
    icon: "hub",
    level: 2,
    col: 0,
    deps: ["working-with-llms"],
    type: "quiz",
    color: "#0ea5e9",
  },
  {
    id: "choosing-right-model",
    title: "Choosing the Right Model",
    shortTitle: "Model Choice",
    description: "Closed models (OpenAI, Anthropic, Google, Cohere) vs open-source models (LLaMA, Mistral, DeepSeek, Qwen, Gemma, etc.) — how to pick the right one for your use case.",
    icon: "model",
    level: 2,
    col: 1,
    deps: ["working-with-llms"],
    type: "quiz",
    color: "#14b8a6",
  },

  // ===== Level 3: Embeddings =====
  {
    id: "embeddings-vector-db",
    title: "Embeddings & Use Cases",
    shortTitle: "Embeddings",
    description: "What are embeddings, semantic search, data classification, recommendation systems, anomaly detection, and common use cases for embeddings.",
    icon: "vector",
    level: 3,
    col: 0,
    deps: ["core-llm-elements"],
    type: "quiz",
    color: "#ec4899",
  },
  {
    id: "embedding-models",
    title: "Embedding Models",
    shortTitle: "Embed Models",
    description: "Proprietary embeddings, open-source embeddings, and the providers & APIs that serve them — how to choose the right embedding model.",
    icon: "embed",
    level: 3,
    col: 1,
    deps: ["embeddings-vector-db"],
    type: "quiz",
    color: "#f472b6",
  },
  {
    id: "vector-databases",
    title: "Vector Databases",
    shortTitle: "Vector DBs",
    description: "Pinecone, Weaviate, FAISS, LanceDB, Milvus, Qdrant, and Elasticsearch for semantic search — when to use each.",
    icon: "vdb",
    level: 3,
    col: 2,
    deps: ["embeddings-vector-db"],
    type: "quiz",
    color: "#db2777",
  },

  // ===== Level 4: Retrieval & RAG =====
  {
    id: "rag",
    title: "RAG (Retrieval Augmented Generation)",
    shortTitle: "RAG",
    description: "What is RAG, data collection, data chunking, embeddings, vector store, retrieval, response generation, and RAG evaluation.",
    icon: "rag",
    level: 4,
    col: 0,
    deps: ["embedding-models", "vector-databases", "prompt-engineering"],
    type: "quiz",
    color: "#d946ef",
  },
  {
    id: "rag-frameworks",
    title: "Ways to Implement RAG",
    shortTitle: "RAG Frameworks",
    description: "LangChain, LlamaIndex, Haystack, and RAGFlow — the frameworks for building production RAG pipelines.",
    icon: "chain",
    level: 4,
    col: 1,
    deps: ["rag"],
    type: "quiz",
    color: "#c026d3",
  },

  // ===== Level 5: Agents & Protocols =====
  {
    id: "ai-agents",
    title: "AI Agents",
    shortTitle: "AI Agents",
    description: "Agent roadmap, reasoning + planning, tool use, multi-agent systems, memory & orchestration, and agent evaluation.",
    icon: "agent",
    level: 5,
    col: 0,
    deps: ["rag-frameworks", "working-with-llms"],
    type: "quiz",
    color: "#06b6d4",
  },
  {
    id: "mcp",
    title: "MCP (Model Context Protocol)",
    shortTitle: "MCP",
    description: "MCP client, MCP server, MCP tools, data layer, and tool discovery & governance — the open standard for connecting AI agents to tools and data.",
    icon: "mcp",
    level: 5,
    col: 1,
    deps: ["ai-agents"],
    type: "quiz",
    color: "#0891b2",
  },

  // ===== Level 6: Safety, Multimodal & Tools =====
  {
    id: "ai-safety-ethics",
    title: "AI Safety & Ethics",
    shortTitle: "Safety & Ethics",
    description: "Prompt injection, jailbreaks, data privacy & governance, guardrails, and red-team testing.",
    icon: "shield",
    level: 6,
    col: 0,
    deps: ["prompt-engineering", "working-with-llms"],
    type: "quiz",
    color: "#10b981",
  },
  {
    id: "multimodal-ai",
    title: "Multimodal AI",
    shortTitle: "Multimodal",
    description: "Image understanding, image generation, video generation, audio processing, text-to-speech, speech-to-text, and multimodal models.",
    icon: "image",
    level: 6,
    col: 1,
    deps: ["platforms-ecosystem", "working-with-llms"],
    type: "quiz",
    color: "#f43f5e",
  },
  {
    id: "dev-tools",
    title: "Development Tools",
    shortTitle: "Dev Tools",
    description: "Claude Code, Copilot, Cursor, Windsurf, and other AI-assisted coding tools that let engineers ship faster.",
    icon: "dev",
    level: 6,
    col: 2,
    deps: ["prompt-engineering"],
    type: "quiz",
    color: "#f59e0b",
  },
];

module.exports = aimlModules;
